name: CI

# 1) Quand lancer le workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # 2) Sur quel runner éxecuter
   runs-on: ubuntu-latest

   steps:
     # 3.1) récupérer ton code
     - name: Checkout code
       uses: actions/checkout@v3

     # 3.2) Installer Java et Maven
     - name: Set up Java 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'

     # 3.3) Construire l'application
     - name: Build with Maven
       run: mvn clean package

     # 3.4) Lancer les tests unitaires
     - name: Run tests
       run: mvn test

     # (Optionnel) 3.5) Publier le JAR pour réutilisation
     - name: Upload JAR artifact
       uses: actions/upload-artifact@v3
       with:
        name: app-jar
        path: target/*.jar